export const styledComponent = {
  body: {
    width: "auto",
    height: "100vh",
    display: "flex",
    flexFlow: "column nowrap",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#eeeeee",
    overflow: "hidden",
  },
  flexBoxStyles: {
    position: "relative",
    width: "100%",
    height: "100%",
    display: "flex",
    flexFlow: "column nowrap",
    justifyContent: "center",
    alignItems: "center",
    // borderRadius: "5px",
    padding: "1rem",
    overflow: "hidden",
  },

  subTitleStyles: {
    fontSize: "1.4rem",
  },
  isGoodWeatherStyles: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexFlow: "column nowrap",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "lightblue",
    padding: "1rem",
    borderRadius: "5px",
    boxShadow: "2px 2px -2px -2px",
  },
  isNotGoodWeatherStyles: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexFlow: "column nowrap",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "lightgrey",
    padding: "1rem",
    borderRadius: "5px",
    boxShadow: "2px 2px -2px -2px",
  },
};
